### ISSUE TITLE
Combine files back to downloadable file/stream

### ISSUE THREAD

**Issue by andrewminton** [shobhitsharma/pptx-compose#1]
This tool looks useful. I'm trying to figure out if it's capable of generating a file for download which has combined multiple pptx files together at all? It creates an array but it isn't clear if this can be converted to a raw binary file for download? thanks.

**Comment by shobhitsharma** [comment]
This https://github.com/shobhitsharma/pptx-compose#bufferize should do it, but you need to make sure attached images should be storied somewhere with reference.
